module Lore
  ( SessionConfig (..),
    SessionConfigError,
    ProjectProvider (..),
    LoreConfig (..),
    DeadCodeConfig (..),
    SymbolSearchConfig (..),
    LoreConfigError (..),
    ConfigError (..),
    LoadedConfigDocument (..),
    SynonymGroupError (..),
    defaultLoreConfig,
    defaultDeadCodeConfig,
    defaultSymbolSearchConfig,
    loadLoreConfig,
    renderLoreConfigError,
    defaultSessionConfig,
    ResolvedStartupConfig (..),
    loadStartupConfig,
    renderSessionConfigError,
    ParallelWorkersCount (..),
    LoreMonadT,
    MonadLore,
    runLore,
    CacheMemorySnapshot (..),
    CacheMemoryStats (..),
    CacheMemoryDebugResult (..),
    debugSessionCachesMemory,
    LoadHomeModulesResult (..),
    LoadHomeModulesOptions (..),
    defaultLoadHomeModulesOptions,
    loadHomeModules,
    lookupLastLoadHomeModulesResult,
    RunTestSuiteOptions (..),
    RunTestSuiteResult (..),
    TestSuiteComponentStatus (..),
    TestSuiteComponentResult (..),
    TestArgumentsParseError (..),
    parseTestArguments,
    renderTestArgumentsParseError,
    runTestSuite,
    NormalizedOccName,
    NormalizedModuleName,
    NormalizedName (occName, moduleName, ownerHint),
    parseAndNormalizeName,
    normalizeModuleName,
    mkNormalizedModuleName,
    Symbol (..),
    SymbolSuggestion (..),
    SymbolVisibility (..),
    ExportedSymbolNode (..),
    SymbolCategory (..),
    classifySymbolCategory,
    SymbolInfo (..),
    Instances (..),
    ChosenInstanceError (..),
    ChosenInstanceResolution (..),
    ChosenInstanceContextStatus (..),
    PathToRoot (..),
    ModulePattern,
    ModulePatternError (..),
    compileModulePattern,
    FindSimilarSymbolsOptions (..),
    findMatchingSymbols,
    findMatchingSymbolLookupNamesByPrefix,
    findProjectModuleNamesByPrefix,
    findSimilarSymbols,
    resolveModule,
    listSymbolsExportedByModule,
    filterExportedSymbolNodesByTypeHint,
    lookupSymbolInfo,
    listIntersectingInstances,
    listAssociatedInstances,
    listDirectInstances,
    resolveChosenClassInstanceFromTypeText,
    resolvePathToRoot,
    -- Source-first definition API.
    resolveDefinitionSourceNamed,
    resolveDefinitionClosureSourcesNamed,
    resolveReferenceMatchesForNames,
    mergeDefinitionSlices,
    findDeadCode,
    DeadCodeOptions (..),
    DeadDefinition (..),
    DeadCodeResult (..),
    DefinitionId (..),
    DefinitionSource (..),
    definitionSourceModule,
    -- Rendering DTO used by existing renderers.
    DefinitionSlice (..),
    ReferenceHit (..),
    NamedDefinitionSource (..),
    DeclarationSpans (..),
    ReferenceMatch (..),
    Diagnostic (..),
    DiagnosticClass (..),
    DiagnosticSpan (..),
    Span (..),
    DiagnosticCodeInfo (..),
    interpreterContextIsReady,
    loadInterpreterContext,
    executeStatement,
    getTypeOfExpression,
    createTemporalModule,
    GhcOption (..),
    Extension (..),
    PackageData (..),
    ComponentKind (..),
    ComponentData (..),
    discoverProject,
    LoggerHandle (..),
    LogLevel (..),
    LogMessage (..),
    prettyLoggerHandle,
    noLogHandle,
  )
where

import Lore.Config
import Lore.DeadCode
import Lore.Definition
import Lore.Diagnostics
import Lore.HomeModules
import Lore.Interpreter
import Lore.Logger
import Lore.Lookup
import Lore.Module
import Lore.Monad (LoreMonadT, MonadLore)
import Lore.Project
import Lore.Session
import Lore.TemporalModules
import Lore.TestSuite
