module Lore
  ( SessionConfig (..),
    defaultSessionConfig,
    ParallelWorkersCount (..),
    LoreMonadT,
    MonadLore,
    runLore,
    LoadTargetsResult (..),
    LoadTargetsOptions (..),
    defaultLoadTargetsOptions,
    loadTargets,
    getLastLoadTargetsResult,
    Symbol (..),
    SymbolVisibility (..),
    ExportedSymbolNode (..),
    RootSymbolInfo (..),
    SymbolCategory (..),
    classifySymbolCategory,
    SymbolInfo (..),
    Instances (..),
    LookupInstancesQuery (..),
    MatchingInstance (..),
    LookupInstancesResult (..),
    findSymbols,
    listExportedSymbolsByModule,
    lookupSymbolInfo,
    lookupRootSymbolInfo,
    lookupRootSymbolInfoWithChain,
    lookupIntersectingInstances,
    lookupIntersectingRootInstances,
    resolveInstances,
    resolveInstanceDefinitions,
    resolveDefinitionSlice,
    resolveReferenceMatches,
    resolveReferenceMatchesForNames,
    resolveReferenceDefinitions,
    resolveReferenceDefinitionsForNames,
    resolveDefinitionClosure,
    mergeDefinitionSlices,
    renderDeclarationSpansText,
    renderDefinitionSliceText,
    renderDefinitionModuleText,
    renderDefinitionModulesText,
    renderImport,
    DefinitionSlice (..),
    DeclarationSpans (..),
    ReferenceMatch (..),
    RequiredImport,
    Diagnostic (..),
    DiagnosticClass (..),
    DiagnosticSpan (..),
    Span (..),
    DiagnosticCodeInfo (..),
    interpreterContextIsReady,
    loadInterpreterContext,
    executeStatement,
    getTypeOfExpression,
    LoggerHandle (..),
    LogLevel (..),
    LogMessage (..),
    prettyLoggerHandle,
    noLogHandle,
  )
where

import Lore.Definition
import Lore.Diagnostics
import Lore.Interpreter
import Lore.Logger
import Lore.Lookup
import Lore.Monad (LoreMonadT, MonadLore)
import Lore.Session
import Lore.Targets
